### ISSUE TITLE
Many tools broken. Revert please.

### ISSUE THREAD

**Issue by samrrr** [methodofaction/Method-Draw#112]
Please revert code to working version.

Now not work complete: grid, preferences, hotkeys, about.
Backspace remove current selected thing. Its really bad idea link to raw input.
Scaling offen desynced with really scale.
Size really float but you show it as int.
Canvas color back ignores alpha.
Export to png change colors.
[railgun_64.zip](https://github.com/methodofaction/Method-Draw/files/6270657/railgun_64.zip)

**Comment by methodofaction** [comment]
> Now not work complete: grid, preferences, hotkeys, about.

* Grid removed
* Configuration stubbed
* Shortcuts screen implemented
* About implemented

> Backspace remove current selected thing. Its really bad idea link to raw input.

I don't agree.

> Scaling offen desynced with really scale.

Not sure what you mean

> Size really float but you show it as int.

Simplicity

> Canvas color back ignores alpha.

 Haven't been able to fix this bug yet

> Export to png change colors.

I see the difference from the sample file, thanks. I'll see where the problem is as this relies on an external library (canvg).

**Comment by samrrr** [comment]
> I don't agree.
you can try erase numbers and watch result.
